/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as GuideIndexImport } from './routes/guide/index'
import { Route as GuideSwitchesImport } from './routes/guide/switches'
import { Route as GuideStabilizersImport } from './routes/guide/stabilizers'
import { Route as GuideKitsImport } from './routes/guide/kits'
import { Route as GuideKeycapsImport } from './routes/guide/keycaps'
import { Route as GuideIntroImport } from './routes/guide/intro'

// Create Virtual Routes

const ResourcesLazyImport = createFileRoute('/resources')()

// Create/Update Routes

const ResourcesLazyRoute = ResourcesLazyImport.update({
  path: '/resources',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/resources.lazy').then((d) => d.Route))

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const GuideIndexRoute = GuideIndexImport.update({
  path: '/guide/',
  getParentRoute: () => rootRoute,
} as any)

const GuideSwitchesRoute = GuideSwitchesImport.update({
  path: '/guide/switches',
  getParentRoute: () => rootRoute,
} as any)

const GuideStabilizersRoute = GuideStabilizersImport.update({
  path: '/guide/stabilizers',
  getParentRoute: () => rootRoute,
} as any)

const GuideKitsRoute = GuideKitsImport.update({
  path: '/guide/kits',
  getParentRoute: () => rootRoute,
} as any)

const GuideKeycapsRoute = GuideKeycapsImport.update({
  path: '/guide/keycaps',
  getParentRoute: () => rootRoute,
} as any)

const GuideIntroRoute = GuideIntroImport.update({
  path: '/guide/intro',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/resources': {
      preLoaderRoute: typeof ResourcesLazyImport
      parentRoute: typeof rootRoute
    }
    '/guide/intro': {
      preLoaderRoute: typeof GuideIntroImport
      parentRoute: typeof rootRoute
    }
    '/guide/keycaps': {
      preLoaderRoute: typeof GuideKeycapsImport
      parentRoute: typeof rootRoute
    }
    '/guide/kits': {
      preLoaderRoute: typeof GuideKitsImport
      parentRoute: typeof rootRoute
    }
    '/guide/stabilizers': {
      preLoaderRoute: typeof GuideStabilizersImport
      parentRoute: typeof rootRoute
    }
    '/guide/switches': {
      preLoaderRoute: typeof GuideSwitchesImport
      parentRoute: typeof rootRoute
    }
    '/guide/': {
      preLoaderRoute: typeof GuideIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  ResourcesLazyRoute,
  GuideIntroRoute,
  GuideKeycapsRoute,
  GuideKitsRoute,
  GuideStabilizersRoute,
  GuideSwitchesRoute,
  GuideIndexRoute,
])

/* prettier-ignore-end */
